const carData = [
{'make': 'Aston martin', 'model': 'DB 11', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'sedan'},
{'make': 'AM', 'model': 'DB 11', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'sedan'},
{'make': 'Aston martin', 'model': 'DB11 V8', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'V12 Vantage', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'sedan'},
{'make': 'Aston martin', 'model': 'DBS Superleggera Volante', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'V8 Vantage', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'Vanquish', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'DB9', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'Rapide', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Aston martin', 'model': 'TT COUPE', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'Q2', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'Q3', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'A3 Cabriolet', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'R8', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A3', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'Q5', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'S8', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A4', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A5', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A6', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'R6', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A7 SPORTBACK', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'E Tron', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'Q8', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'RS 7 SPORTBACK', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'S5', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'RS5', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'Q7', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'A8', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'A8 L', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'SQ7', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'A5 Sportmark', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Audi', 'model': 'RS6', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Bentley', 'model': 'Continental GTC', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Continental Super Sports', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'New Flying spur', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Azure', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Mulsanne Speed', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Mulsanne Extended Wheelbase', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'New Continental GT V8', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Continental Flying Spur', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'New Continental GT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Arnage', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Bentayga', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'SUV'},
{'make': 'Bentley', 'model': 'Z3', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'Z4', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '118D', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'BMW', 'model': '1-Series', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'BMW', 'model': '4-Series', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '3-Series', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'Z2', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'M3', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'i8 ROADSTER', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '5-Series', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'M5', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'X6', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '6-Series', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'M6', 'finalCategory': 'Xtra Large', 'category': 'Premium - 7 Seater', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '2 series', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '8 Series', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'i3', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'M2', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '3 Series GT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'X1', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'BMW', 'model': 'X3', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'BMW', 'model': 'X5', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'BMW', 'model': 'X7', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'BMW', 'model': 'X4', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'Veyron', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '6 Series Grand Turismo', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '7-Series', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': 'M4', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Cadillac', 'model': '7', 'finalCategory': 'Small', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Beat', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Chevrolet', 'model': 'Captiva', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Chevrolet', 'model': 'Aveo U-VA', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Sail Hatchback', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Chevrolet', 'model': 'Agile', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Chevrolet', 'model': 'Sail', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'SRV', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Chevrolet', 'model': 'Enjoy', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Chevrolet', 'model': 'Aveo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Spin', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Chevrolet', 'model': 'Tavera', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Chevrolet', 'model': 'Forester', 'finalCategory': 'Xtra Large', 'category': 'Normal - 7 Seater', 'segment': 'SUV'},
{'make': 'Chevrolet', 'model': 'Optra Magnum', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Cruze', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Impala', 'finalCategory': 'Xtra Large', 'category': 'Normal - 7 Seater', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Swing', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Chevrolet', 'model': 'Corvette', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Fleetline', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'ESSENTIA', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Trailblazer', 'finalCategory': 'Xtra Large', 'category': 'Normal - 7 Seater', 'segment': 'SUV'},
{'make': 'Chrysler', 'model': 'Chrysler 300', 'finalCategory': 'Xtra Large', 'category': 'Normal - 7 Seater', 'segment': 'Sedan'},
{'make': 'Daewoo', 'model': 'Cielo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Daewoo', 'model': 'Nexia', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Datsun', 'model': 'Fiesta(hatchback)', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Datsun', 'model': 'Go', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Datsun', 'model': 'GO-PLUS', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Ferrari', 'model': '575 Super America', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'California', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': '599 GTB Fiorano', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'Cronos', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': '612', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': '812 Superfast', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'FF', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'GTC4LUSSO', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'F12 Berlinetta', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Chevrolet', 'model': 'Spark', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Abarth 595', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Uno', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Palio', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Freestyle', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': '1100', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Fiat', 'model': 'Adventure', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Avventura', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Argo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Grande Punto', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Petra', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Fiat', 'model': 'Sienna', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Fiat', 'model': 'Bravo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Linea', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Fiat', 'model': 'Urbancross', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Fiat', 'model': 'Punto Evo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Force', 'model': 'Gurkha', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Ford', 'model': 'Fiesta', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Fiesta Active', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Ford', 'model': 'Figo 2019', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Ford', 'model': 'Aspire', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Ecosport', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Ford', 'model': 'Fusion', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Escort', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Ikon', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Capri', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Classic', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Mustang', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'MONDEO', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Mondeo sport break', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ford', 'model': 'Endeavour', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Ford', 'model': 'Mustang', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Hindustan_Motors', 'model': 'Contessa', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'CR-X', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'Jazz', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Honda', 'model': 'Amaze', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'WRV', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Honda', 'model': 'Mobilio', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Honda', 'model': 'Concerto', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'City', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'DBX', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'BR - V', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Honda', 'model': 'Jazz ( for FW shield -XL)', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Honda', 'model': 'CR-V', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Honda', 'model': 'CIVIC', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'Step Wagon', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Honda', 'model': 'Accord', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hummer', 'model': 'H2', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Daewoo', 'model': 'Matiz', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Datsun', 'model': 'Redi GO', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Grand I10', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Getz', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Xcent', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'i20', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Venue', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'i10 Nios', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Creta', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'i30', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'HEXA SPACE', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Palisade', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Kona', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Accent', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'VERNA FLUIDIC', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'E pace', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Verna', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'IONIQ', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'Alcazar', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Tuscon', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'New Elantra', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'Santa Fe', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Terracan', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'i40', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Ferrari', 'model': 'f8 tributo', 'finalCategory': 'large', 'category': 'premium', 'segment': 'sedan'},
{'make': 'Ferrari', 'model': '296gts', 'finalCategory': 'large', 'category': 'premium', 'segment': 'sedan'},
{'make': 'Ferrari', 'model': 'roma', 'finalCategory': 'large', 'category': 'premium', 'segment': 'sedan'},
{'make': 'Ferrari', 'model': '286 gtb', 'finalCategory': 'large', 'category': 'premium', 'segment': 'sedan'},
{'make': 'Ferrari', 'model': 'purosangue', 'finalCategory': 'extra large', 'category': 'premium', 'segment': 'suv'},
{'make': 'Ferrari', 'model': '500', 'finalCategory': 'Small', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'Sonata', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'CARLINO', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Creta N Line', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'i20 N Line', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Kona Electric', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Venue N Line', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Exter', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'ICML', 'model': 'Isuzu MU-X', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Isuzu', 'model': 'MU7', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Isuzu', 'model': 'MU-X', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Isuzu', 'model': 'D Max S Cab', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Isuzu', 'model': 'D max V cross', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Jaguar', 'model': 'F type', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Jaguar', 'model': 'XK', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Jaguar', 'model': 'F pace', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Jaguar', 'model': 'XE', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Jaguar', 'model': 'Cerato', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Jaguar', 'model': 'XF', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Jaguar', 'model': 'XJ L', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Honda', 'model': 'Brio', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'KIA', 'model': 'Rio', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'KIA', 'model': 'Optima', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'KIA', 'model': 'Niro', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Soul', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Sportage', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Stonic', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Sorento', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Stinger', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'KIA', 'model': 'Sonet', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'KIA', 'model': 'Seltos', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Carnival', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Carens', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'RENEGADE', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'JEEP CAMPASS', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'New Wrangler', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'Wrangler', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'Grand Cherokee', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lamborghini', 'model': 'NX', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lamborghini', 'model': 'Murcielago', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lamborghini', 'model': 'Urus', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lamborghini', 'model': 'Aventador', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Land Rover', 'model': 'Freelander 2', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Range Sport', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Discovery Sport', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Defender 90 Variant', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Defender 110 Variant', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'RANGE ROVER VELAR', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Discovery 4', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Range Rover', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'GX 460', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'LX 470', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'SC 470', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'ES', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'GS 300', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'RX', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'LS 460', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'LS 400', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'LS 430', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'UX', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'LS 600', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'Santro Xing', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'KUV 100', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'Thar', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Jeep', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Nuvosport', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'Quanto', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'Verito Vibe', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Mahindra', 'model': 'TUV 300', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Bolero', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Alturas G4', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Logan', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Mahindra', 'model': 'Verito', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'XUV300', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Marazzo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Armada', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Scorpio', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Marshal', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Xylo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'XUV500', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Scorpio Getaway', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Thar Roxx', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Bolero Neo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'Scorpio N', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'XUV400', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': '3XO', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Omni', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'i10', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'Santro2018', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hyundai', 'model': 'EON', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'WAGNOR', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Wagon R 1', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'JIMNY', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Picanto', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'KIA', 'model': 'ceed', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Eeco', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Versa', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Ignis', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Ritz', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'SWIFT AMT', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Baleno Hatchback', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Lexus', 'model': 'RC F', 'finalCategory': 'Small', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'WAGNOR YJC', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Swift DZire', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Grand Vitara', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Brezza', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Gypsy', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': '1000', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Esteem', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Baleno Sedan', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Ertiga', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'S Cross', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Ciaz', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'SX4', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Celerio X', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Celerio', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Ertiga New', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'e2O', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'e20 plus', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Swift', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'XL6', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'REVA', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Wagon R 2019', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Alto 800', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Kizashi', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Fronx', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Invicto', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Grand Vitara XL7', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maserati', 'model': 'CLA Class', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maserati', 'model': 'Gran Turismo', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maserati', 'model': 'Ghibli', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maserati', 'model': 'Quattropote', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maserati', 'model': '62', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maybach', 'model': '57 S', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'SLC', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'GLC', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'M Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'EQC', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'RX5', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLC COUPE', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'S Coupe', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'V Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'FLS-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'A-class', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'B-class', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'GL', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLA 200', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'AMG-GT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'G-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'C-Class', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'M Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'ML-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLE', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'R-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'CLS', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'SLK-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'Viano', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'E-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'S-Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mini', 'model': 'Convertible', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mini', 'model': 'Eclipse Cross', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Mini', 'model': 'Countryman', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mini', 'model': 'S', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Mini', 'model': 'Colt', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Mitsubishi', 'model': 'Lancer', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mitsubishi', 'model': 'Lancer Evolution', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mitsubishi', 'model': 'Cedia', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mitsubishi', 'model': 'NEW PAJERO SPROTS', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mitsubishi', 'model': 'Outlander', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mitsubishi', 'model': 'Montero', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mitsubishi', 'model': 'Leaf', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mitsubishi', 'model': 'Pajero', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mitsubishi', 'model': 'Mirage G4', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Nissan', 'model': 'Micra', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Nissan', 'model': '370Z', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'KICKS', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Fairlady', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Laurel', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': '350Z', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Gloria', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Evalia', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Cedric', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Sunny', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'X-TRAIL', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Note E Power', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Nissan', 'model': 'Juke', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Nissan', 'model': 'GTR', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Teana', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Cima', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Nissan', 'model': 'Terrano', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Zen', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Opel', 'model': 'Astra', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Opel', 'model': 'Vectra', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Opel', 'model': '309', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Peugeot', 'model': 'Boxster', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Porsche', 'model': 'Cayman', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Porsche', 'model': '911', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Porsche', 'model': 'Cayenne', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Porsche', 'model': 'Zoe', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Porsche', 'model': 'MACAN TURBO EV', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SEDAN'},
{'make': 'Porsche', 'model': 'TAYCAN', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Porsche', 'model': 'Panamera', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Renault', 'model': 'Triber', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Renault', 'model': 'Pulse', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Renault', 'model': 'CAPTUR', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Renault', 'model': 'Duster', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Renault', 'model': 'Scala', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Renault', 'model': 'Lodgy', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Renault', 'model': 'Fluence', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Renault', 'model': 'Wraith', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Dawn', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Ghost Series 2', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Arona', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Drophead Coupe', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Ghost', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Phantom Drophead Coupe', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Rolls Royce', 'model': 'Phantom', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'A-Star', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Zen Estilo', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Skoda', 'model': 'Roomster', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Skoda', 'model': 'Yeti', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Skoda', 'model': 'Fabia', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Skoda', 'model': 'Rapid', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Skoda', 'model': 'Octavia', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Skoda', 'model': 'Laura', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Skoda', 'model': 'KODIAQ', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Skoda', 'model': '45X Hatchback', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Skoda', 'model': 'Superb', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Spyker', 'model': 'C8 Spyder', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Spyker', 'model': 'Peckingtoparis', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Spyker', 'model': 'TIVOLI', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Indica V2 Xeta', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Indica', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Tiago', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Indica Vista', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Bolt', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'RACEMO', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Venture', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Indigo eCS', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Tigor', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Zest', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'NEXON (OSPREY)', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Nexon', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Sumo', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Sierra', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Manza', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Sumo Grande MK II', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Safari', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Curve', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Aria', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Hexa', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Gen X Nano', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Safari Storme', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Winger', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Harrier', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Tata', 'model': 'Xenon XT', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': 'Celario', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Kite Compact Sedan', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Sera', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Etios Cross', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Toyota', 'model': 'MR2', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Tercel', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Cynos', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'CeliCa', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Etios', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'VIOS', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Qualis', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Camry', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Master Ace', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Prius', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Corona', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Cressida', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Rav-4', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Corolla Altis', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Glanza', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Toyota', 'model': 'Estima', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Fortuner', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Innova Crysta', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Crown', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Land Cruiser Prado', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Virtus', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Land Cruiser', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'MaJEsta', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Commuter', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Yaris', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Hyryder', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'Polo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Volkswagen', 'model': 'Cross Polo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Volkswagen', 'model': 'Beetle', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': 'Vento', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': 'Taigun', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'Ameo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': 'Jetta', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': 'New Polo GT Line', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Volkswagen', 'model': 'T Cross', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'Passat', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': 'Touareg', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'PASSAT GTE', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'Rocktan', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Volkswagen', 'model': 'Caravelle', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'Phaeton', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volkswagen', 'model': '1600', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'V40 Cross Country', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Volvo', 'model': 'S40', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'V50', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'C70', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'S60', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'XC60', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'V70', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'V90 Cross Country', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'S80', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'XC40', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'S960', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'XC90', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'S90', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Volvo', 'model': 'V 40 Cross Country', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Volvo', 'model': 'MB', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLC-Class', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'Maybach S Class', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'LX', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Discovery', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'S-Class Coupe', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Citroen', 'model': 'Sandero', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Dacia', 'model': 'DS3 Crossback', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'MG', 'model': 'GS', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'MG', 'model': 'ERX5', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mini Cooper', 'model': 'Clubman', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'MG', 'model': 'Hector', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Seltos', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Seat', 'model': 'Vision X', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Jaguar', 'model': 'XE 2019', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Hyundai', 'model': 'Alcazar', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'XUV700', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Audi', 'model': 'RS 6 AVANT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Audi', 'model': 'TT', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Bentley', 'model': 'Continental GT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'BMW', 'model': '6series GT', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Cadillac', 'model': 'CTS', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Cervo', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Citroen', 'model': 'C5 Aircross', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Alto', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maruti Suzuki', 'model': 'Alto 2019', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Datsun', 'model': 'GO-CROSS', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'DC', 'model': 'Avanti', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': 'Portofino', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': '458 Italia', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Ferrari', 'model': '488', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Force', 'model': 'Force One', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Ford', 'model': 'Figo', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hindustan_Motors', 'model': 'Ambassador', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Alto K10', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Hummer', 'model': 'H3', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Hyundai', 'model': 'Aura', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'S Presso', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Isuzu', 'model': 'DMAX Vcross', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Jeep', 'model': 'Compass', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Carnival', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Maruti Suzuki', 'model': '800', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'KIA', 'model': 'Sonet', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Lamborghini', 'model': 'Gallardo', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lamborghini', 'model': 'Huracan', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Land Rover', 'model': 'Evoque 2019', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Land Rover', 'model': 'Range Evoque', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Land Rover', 'model': 'Range Rover Sport', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'ES', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Lexus', 'model': 'Lexus NX300H', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Lexus', 'model': 'Lexus rc', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maruti Suzuki', 'model': 'Spresso', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Nissan', 'model': 'Jonga', 'finalCategory': 'Small', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Pixo', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'Rexton', 'finalCategory': 'Xtra Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Test', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Renault', 'model': 'Kwid', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Maserati', 'model': 'GranCabrio', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Maserati', 'model': 'Levante', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLA Class', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Mercedes Benz', 'model': 'GLC 300', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLC43', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'GLE 250', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'GLE 300', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Mercedes Benz', 'model': 'GLS', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Mercedes Benz', 'model': 'SLS', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'MG', 'model': 'Gloster', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'MG', 'model': 'Hector Plus', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'MG', 'model': 'Hector', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Mini', 'model': 'Cooper', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Hatchback'},
{'make': 'Rolls Royce', 'model': 'Storm', 'finalCategory': 'Small', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'San', 'model': 'Citigo', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Opel', 'model': 'Corsa', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Porsche', 'model': 'Panamera sport turismo', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Premier', 'model': 'PadMini', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Pelican', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Renault', 'model': 'Kiger', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Rolls Royce', 'model': 'Cullinan', 'finalCategory': 'Xtra Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Skoda', 'model': 'Kushaq', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Spyker', 'model': 'Laviolette', 'finalCategory': 'Medium', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Tata', 'model': 'Nano', 'finalCategory': 'Small', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Altroz', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tesla', 'model': 'Model 3', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Etios Liva', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Toyota', 'model': 'Innova', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'Mach 2', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Sedan'},
{'make': 'Toyota', 'model': 'Urban Cruiser', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volkswagen', 'model': 'TIGUAN', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'S60 Cross Country', 'finalCategory': 'Large', 'category': 'Premium', 'segment': 'Sedan'},
{'make': 'MG', 'model': 'Astor', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Tata', 'model': 'Punch', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'MG', 'model': 'ZSEV', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'KIA', 'model': 'Carens', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Nissan', 'model': 'Magnite', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'Scorpion-N', 'finalCategory': 'Large', 'category': 'Normal', 'segment': 'SUV'},
{'make': 'Citroen', 'model': 'C3', 'finalCategory': 'Medium', 'category': 'Normal', 'segment': 'Hatchback'},
{'make': 'Mahindra', 'model': 'BE6', 'finalCategory': 'LARGE', 'category': 'NORMAL', 'segment': 'SUV'},
{'make': 'Mahindra', 'model': 'XEV9E', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Honda', 'model': 'ELEVATE', 'finalCategory': 'LARGE', 'category': 'NORMAL', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'EX 40', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'Volvo', 'model': 'C40', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SUV'},
{'make': 'BMW', 'model': 'I7', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SEDAN'},
{'make': 'BMW', 'model': 'I5', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SEDAN'},
{'make': 'Skoda', 'model': 'SLAVIA', 'finalCategory': 'LARGE', 'category': 'Premium', 'segment': 'SEDAN'},
{'make': 'Toyota', 'model': 'RUMION', 'finalCategory': 'LARGE', 'category': 'NORMAL', 'segment': 'SUV'},
{'make': 'Toyota', 'model': 'HILUX', 'finalCategory': 'XTRA LARGE', 'category': 'PREMIUM', 'segment': 'SUV'},
{'make': 'MG', 'model': 'WINDSOR', 'finalCategory': 'NORMAL', 'category': 'PREMIUM', 'segment': 'SUV'},
{'make': 'MG', 'model': 'COMET', 'finalCategory': 'NORMAL', 'category': 'PREMIUM', 'segment': 'HATCHBACK'},
{'make': 'Rolls Royce', 'model': 'SPECTRE', 'finalCategory': 'XTRA LARGE', 'category': 'PREMIUM', 'segment': 'SEDAN'},
{'make': 'KIA', 'model': 'syros', 'finalCategory': 'large', 'category': 'normal', 'segment': 'suv'},
{'make': 'KIA', 'model': 'ev6', 'finalCategory': 'large', 'category': 'PREMIUM', 'segment': 'suv'},
{'make': 'KIA', 'model': 'ev9', 'finalCategory': 'large', 'category': 'PREMIUM', 'segment': 'suv'},
{'make': 'Lexus', 'model': 'NX', 'finalCategory': 'large', 'category': 'PREMIUM', 'segment': 'suv'},
{'make': 'Lexus', 'model': 'LM', 'finalCategory': 'LARGE', 'category': 'PREMIUM', 'segment': 'SUV'},
];

// DOM Elements 1
const carMakeDropdown = document.getElementById("car-mk");
const carModelDropdown = document.getElementById("car-md");
const segmentField = document.getElementById("segment");
const categoryField = document.getElementById("category");
const classField = document.getElementById("classs"); // Ensure this matches the input ID

// Populate Car Make dropdown
const uniqueMakes = [...new Set(carData.map(car => car.make))];
uniqueMakes.forEach(make => {
const option = document.createElement("option");
option.value = make;
option.textContent = make;
carMakeDropdown.appendChild(option);
});

// Event listener for Car Make dropdown
carMakeDropdown.addEventListener("change", () => {
console.log("Car Make dropdown value changed");

// Clear and disable the Car Model dropdown
carModelDropdown.innerHTML = "<option value=''>Select Car Model</option>";
carModelDropdown.disabled = true;

// Clear other fields
segmentField.value = "";
categoryField.value = "";
classField.value = "";

// Filter models based on selected make
const selectedMake = carMakeDropdown.value;
const filteredModels = carData.filter(car => car.make === selectedMake);

// Populate and enable Car Model dropdown if models exist
if (filteredModels.length > 0) {
  filteredModels.forEach(car => {
    const option = document.createElement("option");
    option.value = car.model;
    option.textContent = car.model;
    carModelDropdown.appendChild(option);
  });
  carModelDropdown.disabled = false; // Enable dropdown
} else {
  const option = document.createElement("option");
  option.textContent = "No models available";
  carModelDropdown.appendChild(option);
}
});

// Event listener for Car Model dropdown
carModelDropdown.addEventListener("change", () => {
// Clear fields
segmentField.value = "";
categoryField.value = "";
classField.value = "";

// Populate fields based on selected model
const selectedMake = carMakeDropdown.value;
const selectedModel = carModelDropdown.value;
const carDetails = carData.find(car => car.make === selectedMake && car.model === selectedModel);

if (carDetails) {
  // Populate the fields with the car details
  segmentField.value = carDetails.segment;   // Segment field
  categoryField.value = carDetails.category; // Category field
  classField.value = carDetails.finalCategory; // Final Category field
}
});
